import { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
  BrainCircuit, Sparkles, FileText, BarChart3, ArrowRight,
  Briefcase, Mic, Radio, Volume2, Cpu, Check, X, Menu,
  HelpCircle, ChevronDown, Award, Zap, Shield, Target,
} from 'lucide-react';
import { useAuthStore } from '@/store/authStore';
import { ThemeToggle } from '@/components/common';
import AiVoiceInterviewShowcase from '@/components/home/AiVoiceInterviewShowcase';
import CompanyMarquee from '@/components/home/CompanyMarquee';
import SkillsMarquee from '@/components/home/SkillsMarquee';
import StudentReviews from '@/components/home/StudentReviews';

const FEATURES = [
  {
    icon: Mic,
    title: '3D AI Voice Interviewer',
    desc: 'Practice spoken technical interviews with realistic neural speech synthesis, live mic recognition, and real-time audio reactions.',
    color: 'from-brand-600 to-accent-600',
  },
  {
    icon: FileText,
    title: 'Resume-Aware Questions',
    desc: 'Upload your resume and get interview questions tailored to your actual experience, projects, and verified tech stack.',
    color: 'from-accent-600 to-brand-600',
  },
  {
    icon: BrainCircuit,
    title: 'AI-Powered Question Engine',
    desc: 'Questions generated by Llama-3 via Groq — covering deep technical, distributed system design, situational & behavioral formats.',
    color: 'from-emerald-600 to-teal-600',
  },
  {
    icon: BarChart3,
    title: 'Instant Feedback & Scores',
    desc: 'Get detailed AI feedback, ATS keyword match scores, and a question-by-question performance analysis after every answer.',
    color: 'from-amber-600 to-orange-600',
  },
];

const COMPARISONS = [
  {
    feature: 'Available 24/7 on Demand',
    interviewAI: true,
    humanMocks: false,
    textOnlyAI: true,
  },
  {
    feature: 'Real-time Spoken 3D Voice & Audio',
    interviewAI: true,
    humanMocks: true,
    textOnlyAI: false,
  },
  {
    feature: 'Resume & Job Description Tailoring',
    interviewAI: true,
    humanMocks: 'Varies',
    textOnlyAI: 'Basic',
  },
  {
    feature: 'Instant ATS Keyword & STAR Scoring',
    interviewAI: true,
    humanMocks: false,
    textOnlyAI: 'Delayed',
  },
  {
    feature: 'Cost per Mock Session',
    interviewAI: 'Free to Start',
    humanMocks: '$150 - $300 / hr',
    textOnlyAI: 'Subscription',
  },
  {
    feature: 'Zero Judgment, Unlimited Retakes',
    interviewAI: true,
    humanMocks: false,
    textOnlyAI: true,
  },
];

const STEPS = [
  { step: '01', title: 'Create Account & Upload Resume', desc: 'Sign up in seconds and parse your tech stack, projects, and experience automatically.' },
  { step: '02', title: 'Pick Job Description & Skills', desc: 'Target any software role, select experience level, and choose voice or text mode.' },
  { step: '03', title: 'Practice & Get Hired', desc: 'Answer questions with live AI coaching, refine answers, and ace your real interviews.' },
];

const FAQS = [
  {
    q: 'How does the 3D AI Voice Interviewer work?',
    a: 'Our platform uses Web Speech recognition to transcribe your answers in real time, passes them to a low-latency Groq Llama-3 model for deep technical analysis, and responds with dynamic neural voice synthesis accompanied by 3D audio-reactive avatar animations.',
  },
  {
    q: 'Can I practice interviews for my specific tech stack?',
    a: 'Yes! We support 60+ programming languages, frameworks, databases, and cloud platforms — including React, Python, Go, Java, TypeScript, AWS, Kubernetes, and System Design. You can also paste any custom Job Description for hyper-targeted questions.',
  },
  {
    q: 'How does the Resume ATS Scoring work?',
    a: 'When you upload your resume (PDF/DOCX), our engine extracts your skills, work history, and achievements. It compares your resume against target job requirements, highlighting missing keywords, match percentage, and customized interview drills.',
  },
  {
    q: 'Is this free to use for students and job seekers?',
    a: 'Yes! You can get started immediately with free mock sessions and full access to voice simulation. No credit card required.',
  },
  {
    q: 'What formats of interview questions are supported?',
    a: 'We support Coding & Algorithm questions, Distributed System Design, Behavioral & Leadership (STAR method), Framework Deep-Dives, and Live Debugging scenarios.',
  },
];

export default function LandingPage() {
  const { isAuthenticated } = useAuthStore();
  const [openFaq, setOpenFaq] = useState(null);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <div className="min-h-screen bg-surface overflow-x-hidden">
      {/* ── Navbar ──────────────────────────────────────────────── */}
      <nav className="fixed top-0 w-full z-50 bg-surface/90 backdrop-blur-md border-b border-surface-border">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2.5 group">
            <div className="w-8 h-8 rounded-xl overflow-hidden shadow-brand flex items-center justify-center border border-brand-400/30 group-hover:scale-105 transition-transform flex-shrink-0">
              <img src="/AI-interview-svg-icon.png" alt="InterviewAI" className="w-full h-full object-cover" />
            </div>
            <span className="font-display font-bold text-lg gradient-text">InterviewAI</span>
          </Link>

          {/* Desktop Nav Links */}
          <div className="hidden md:flex items-center gap-6 lg:gap-8">
            <a href="#skills-section" className="text-sm font-medium text-slate-400 hover:text-white transition-colors">
              Skills
            </a>
            <a href="#features-section" className="text-sm font-medium text-slate-400 hover:text-white transition-colors">
              Features
            </a>
            <a href="#reviews-section" className="text-sm font-medium text-slate-400 hover:text-white transition-colors">
              Reviews
            </a>
            <a href="#faq-section" className="text-sm font-medium text-slate-400 hover:text-white transition-colors">
              FAQ
            </a>
            <Link to="/jobs" className="text-sm font-medium text-slate-400 hover:text-white transition-colors flex items-center gap-2">
              <Briefcase className="w-4 h-4" />
              Jobs
              <span className="text-[10px] bg-brand-600/20 text-brand-400 px-1.5 py-0.5 rounded border border-brand-500/20 font-bold uppercase tracking-tight">
                Soon
              </span>
            </Link>
          </div>

          {/* Desktop Right Actions */}
          <div className="hidden sm:flex items-center gap-3">
            {isAuthenticated ? (
              <Link to="/dashboard" className="btn-primary text-xs sm:text-sm px-4 py-2 sm:px-5 sm:py-2.5">Go to Dashboard</Link>
            ) : (
              <>
                <Link to="/login" className="btn-ghost text-xs sm:text-sm">Sign In</Link>
                <Link to="/register" className="btn-primary text-xs sm:text-sm px-4 py-2 sm:px-5 sm:py-2.5">Get Started</Link>
              </>
            )}
            <ThemeToggle />
          </div>

          {/* Mobile Right Controls: Theme + Hamburger */}
          <div className="flex sm:hidden items-center gap-2">
            <ThemeToggle />
            <button
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 border border-surface-border transition-colors"
              aria-label="Toggle navigation menu"
            >
              {mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </button>
          </div>
        </div>

        {/* Mobile Dropdown Drawer */}
        <AnimatePresence>
          {mobileMenuOpen && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.25 }}
              className="md:hidden border-b border-surface-border bg-surface-card/95 backdrop-blur-xl px-5 pt-3 pb-6 space-y-4"
            >
              <div className="flex flex-col space-y-2">
                <a
                  href="#skills-section"
                  onClick={() => setMobileMenuOpen(false)}
                  className="py-2 text-sm font-medium text-slate-300 hover:text-brand-400 transition-colors"
                >
                  Skills
                </a>
                <a
                  href="#features-section"
                  onClick={() => setMobileMenuOpen(false)}
                  className="py-2 text-sm font-medium text-slate-300 hover:text-brand-400 transition-colors"
                >
                  Features
                </a>
                <a
                  href="#reviews-section"
                  onClick={() => setMobileMenuOpen(false)}
                  className="py-2 text-sm font-medium text-slate-300 hover:text-brand-400 transition-colors"
                >
                  Reviews
                </a>
                <a
                  href="#faq-section"
                  onClick={() => setMobileMenuOpen(false)}
                  className="py-2 text-sm font-medium text-slate-300 hover:text-brand-400 transition-colors"
                >
                  FAQ
                </a>
                <Link
                  to="/jobs"
                  onClick={() => setMobileMenuOpen(false)}
                  className="py-2 text-sm font-medium text-slate-300 hover:text-brand-400 transition-colors flex items-center justify-between"
                >
                  <span className="flex items-center gap-2">
                    <Briefcase className="w-4 h-4 text-brand-400" />
                    Jobs Portal
                  </span>
                  <span className="text-[10px] bg-brand-600/20 text-brand-400 px-2 py-0.5 rounded font-bold">
                    SOON
                  </span>
                </Link>
              </div>

              <div className="pt-3 border-t border-surface-border flex flex-col gap-2.5">
                {isAuthenticated ? (
                  <Link
                    to="/dashboard"
                    onClick={() => setMobileMenuOpen(false)}
                    className="btn-primary w-full text-center py-2.5"
                  >
                    Go to Dashboard
                  </Link>
                ) : (
                  <>
                    <Link
                      to="/login"
                      onClick={() => setMobileMenuOpen(false)}
                      className="btn-secondary w-full text-center py-2.5"
                    >
                      Sign In
                    </Link>
                    <Link
                      to="/register"
                      onClick={() => setMobileMenuOpen(false)}
                      className="btn-primary w-full text-center py-2.5"
                    >
                      Get Started Free
                    </Link>
                  </>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </nav>

      {/* ── Hero ─────────────────────────────────────────────────── */}
      <section className="relative pt-24 sm:pt-28 pb-12 sm:pb-16 px-4 sm:px-6 overflow-hidden">
        {/* Glowing ambient light orbs */}
        <div className="absolute top-16 left-1/2 -translate-x-1/2 w-[90vw] max-w-[700px] h-[300px] sm:h-[450px] bg-brand-500/15 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-36 right-1/4 w-60 sm:w-80 h-60 sm:h-80 bg-accent-600/15 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-64 left-1/4 w-52 sm:w-72 h-52 sm:h-72 bg-brand-400/10 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-6xl mx-auto text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
          >
            <span className="badge-brand badge mb-4 sm:mb-6 inline-flex items-center gap-2 px-3 py-1 sm:px-3.5 sm:py-1.5 rounded-full border border-brand-500/20 bg-brand-500/10 backdrop-blur-md shadow-sm text-xs">
              <img src="/AI-interview-svg-icon.png" alt="Icon" className="w-4 h-4 rounded-sm object-cover flex-shrink-0" />
              <span className="truncate">Interactive 3D Simulation • Real-Time Voice Intelligence</span>
            </span>

            <h1 className="text-3xl xs:text-4xl sm:text-6xl lg:text-7xl font-display font-bold text-white leading-[1.15] mb-4 sm:mb-6">
              Practice Today,<br />
              <span className="gradient-text">Get Hired Tomorrow</span>
            </h1>

            <p className="text-base sm:text-xl text-slate-400 max-w-2xl mx-auto mb-6 sm:mb-8 leading-relaxed px-2">
              Upload your resume, paste a job description, and practice with our {' '}
              <strong className="text-white">3D AI Voice Interviewer</strong> featuring speech synthesis, live mic recognition, and real-time ATS feedback.
            </p>

            <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-center gap-3.5 mb-6 max-w-md sm:max-w-none mx-auto">
              <Link to="/register" className="btn-primary text-sm sm:text-base px-6 sm:px-8 py-3.5 sm:py-4 shadow-lg shadow-brand-500/25 flex items-center justify-center">
                Start Practicing Free <ArrowRight className="w-4 h-4 sm:w-5 sm:h-5 ml-1" />
              </Link>
              <a
                href="#interactive-demo"
                className="btn-secondary text-sm sm:text-base px-6 sm:px-8 py-3.5 sm:py-4 flex items-center justify-center gap-2"
              >
                <Radio className="w-4 h-4 text-brand-400 animate-pulse" /> Try Voice Assistant Demo
              </a>
            </div>

            <p className="text-slate-500 text-xs mb-8 sm:mb-10">
              No credit card required • WebGL 3D Interactive • Works on all modern browsers
            </p>

            {/* ── 3D AI Interview & Voice Assistant Showcase ── */}
            <div id="interactive-demo" className="pt-2">
              <AiVoiceInterviewShowcase />
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── Companies Marquee ─────────────────────────────────────── */}
      <CompanyMarquee />

      {/* ── Flowing Skills Marquee ─────────────────────────────────── */}
      <div id="skills-section">
        <SkillsMarquee />
      </div>

      {/* ── Features ─────────────────────────────────────────────── */}
      <section id="features-section" className="py-24 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-500/10 border border-brand-500/20 text-brand-400 text-xs font-semibold uppercase tracking-wider mb-4">
              <Zap className="w-3.5 h-3.5" />
              Platform Capabilities
            </div>
            <h2 className="text-3xl sm:text-4xl font-display font-bold text-white mb-4">
              Everything you need to <span className="gradient-text">prepare</span>
            </h2>
            <p className="text-slate-400 max-w-xl mx-auto">
              A complete AI interview prep platform with interactive 3D simulations, real-time voice feedback, and deep algorithmic evaluation.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {FEATURES.map(({ icon: Icon, title, desc, color }, i) => (
              <motion.div
                key={title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="card-hover p-6 group flex flex-col justify-between"
              >
                <div>
                  <div className={`w-12 h-12 rounded-2xl bg-gradient-to-br ${color} flex items-center justify-center mb-5 shadow-card group-hover:shadow-glow transition-shadow`}>
                    <Icon className="w-6 h-6 text-white" />
                  </div>
                  <h3 className="text-base font-semibold text-white mb-2">{title}</h3>
                  <p className="text-slate-400 text-xs leading-relaxed">{desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Why Us / Comparison Matrix ────────────────────────────── */}
      <section className="py-16 sm:py-20 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-10 sm:mb-14">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent-500/10 border border-accent-500/20 text-accent-400 text-xs font-semibold uppercase tracking-wider mb-4">
              <Shield className="w-3.5 h-3.5" />
              The Smart Way to Practice
            </div>
            <h2 className="text-2xl sm:text-4xl font-display font-bold text-white mb-4">
              Why Choose <span className="gradient-text">InterviewAI</span>?
            </h2>
            <p className="text-slate-400 max-w-lg mx-auto text-xs sm:text-base px-2">
              Compare how our interactive 3D platform outperforms expensive human coaches and basic text chatbots.
            </p>
          </div>

          <div className="overflow-x-auto rounded-2xl border border-surface-border bg-surface-card shadow-card -mx-2 sm:mx-0">
            <table className="w-full min-w-[540px] text-left border-collapse text-xs sm:text-sm">
              <thead>
                <tr className="border-b border-surface-border bg-surface-card-muted">
                  <th className="py-3 sm:py-4 px-4 sm:px-6 text-slate-300 font-semibold">Key Capabilities</th>
                  <th className="py-4 px-6 text-teal-400 font-bold bg-brand-500/10 text-center">
                    InterviewAI (3D Voice)
                  </th>
                  <th className="py-4 px-6 text-slate-400 font-medium text-center">
                    Human Mock Coach
                  </th>
                  <th className="py-4 px-6 text-slate-400 font-medium text-center">
                    Generic Text AI
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-border">
                {COMPARISONS.map((row, idx) => (
                  <tr key={idx} className="hover:bg-surface-hover/50 transition-colors">
                    <td className="py-4 px-6 font-medium text-slate-200">
                      {row.feature}
                    </td>
                    <td className="py-4 px-6 bg-brand-500/[0.04] text-center">
                      {typeof row.interviewAI === 'boolean' ? (
                        row.interviewAI ? (
                          <span className="inline-flex p-1 rounded-full bg-emerald-500/15 text-emerald-400">
                            <Check className="w-4 h-4 font-bold" />
                          </span>
                        ) : (
                          <span className="inline-flex p-1 rounded-full bg-rose-500/15 text-rose-400">
                            <X className="w-4 h-4" />
                          </span>
                        )
                      ) : (
                        <span className="font-semibold text-emerald-400">{row.interviewAI}</span>
                      )}
                    </td>
                    <td className="py-4 px-6 text-center text-slate-400">
                      {typeof row.humanMocks === 'boolean' ? (
                        row.humanMocks ? (
                          <span className="inline-flex p-1 rounded-full bg-emerald-500/15 text-emerald-400">
                            <Check className="w-4 h-4" />
                          </span>
                        ) : (
                          <span className="inline-flex p-1 rounded-full bg-rose-500/15 text-rose-400">
                            <X className="w-4 h-4" />
                          </span>
                        )
                      ) : (
                        <span className="text-slate-400">{row.humanMocks}</span>
                      )}
                    </td>
                    <td className="py-4 px-6 text-center text-slate-400">
                      {typeof row.textOnlyAI === 'boolean' ? (
                        row.textOnlyAI ? (
                          <span className="inline-flex p-1 rounded-full bg-emerald-500/15 text-emerald-400">
                            <Check className="w-4 h-4" />
                          </span>
                        ) : (
                          <span className="inline-flex p-1 rounded-full bg-rose-500/15 text-rose-400">
                            <X className="w-4 h-4" />
                          </span>
                        )
                      ) : (
                        <span className="text-slate-400">{row.textOnlyAI}</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* ── How It Works ─────────────────────────────────────────── */}
      <section className="py-24 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-500/10 border border-brand-500/20 text-brand-400 text-xs font-semibold uppercase tracking-wider mb-4">
              <Target className="w-3.5 h-3.5" />
              Simple Workflow
            </div>
            <h2 className="text-3xl sm:text-4xl font-display font-bold text-white mb-4">
              From zero to <span className="gradient-text">interview-ready</span>
            </h2>
            <p className="text-slate-400">Three simple steps to supercharge your technical interview practice</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {STEPS.map(({ step, title, desc }, i) => (
              <motion.div key={step}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.15 }}
                className="text-center p-6 rounded-2xl bg-surface-card border border-surface-border relative group hover:border-brand-500/40 transition-colors"
              >
                <div className="w-14 h-14 bg-gradient-brand rounded-2xl flex items-center justify-center mx-auto mb-5 shadow-brand group-hover:scale-110 transition-transform">
                  <span className="text-white font-display font-bold text-lg">{step}</span>
                </div>
                <h3 className="text-lg font-semibold text-white mb-2">{title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed">{desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Student Reviews & Testimonials ───────────────────────── */}
      <div id="reviews-section">
        <StudentReviews />
      </div>

      {/* ── Frequently Asked Questions ───────────────────────────── */}
      <section id="faq-section" className="py-20 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-14">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-500/10 border border-brand-500/20 text-brand-400 text-xs font-semibold uppercase tracking-wider mb-4">
              <HelpCircle className="w-3.5 h-3.5" />
              Got Questions?
            </div>
            <h2 className="text-3xl sm:text-4xl font-display font-bold text-white mb-4">
              Frequently Asked <span className="gradient-text">Questions</span>
            </h2>
            <p className="text-slate-400 text-sm sm:text-base">
              Everything you need to know about preparing with InterviewAI.
            </p>
          </div>

          <div className="space-y-4">
            {FAQS.map((faq, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div
                  key={idx}
                  className="rounded-2xl bg-surface-card border border-surface-border overflow-hidden transition-colors"
                >
                  <button
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    className="w-full py-4 px-6 flex items-center justify-between text-left font-semibold text-white text-base hover:text-brand-300 transition-colors"
                  >
                    <span>{faq.q}</span>
                    <ChevronDown
                      className={`w-5 h-5 text-slate-400 transition-transform duration-200 flex-shrink-0 ml-4 ${
                        isOpen ? 'rotate-180 text-brand-400' : ''
                      }`}
                    />
                  </button>
                  <AnimatePresence>
                    {isOpen && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        transition={{ duration: 0.2 }}
                      >
                        <div className="px-6 pb-5 pt-1 text-slate-300 text-sm leading-relaxed border-t border-surface-border/50">
                          {faq.a}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── CTA ──────────────────────────────────────────────────── */}
      <section className="py-16 sm:py-24 px-4 sm:px-6 text-center relative overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[90vw] max-w-[600px] h-[250px] sm:h-[300px] bg-brand-500/15 rounded-full blur-3xl pointer-events-none" />
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          className="max-w-2xl mx-auto relative z-10"
        >
          <div className="w-14 h-14 sm:w-16 sm:h-16 rounded-2xl p-1 bg-gradient-to-br from-brand-500/20 via-accent-600/30 to-teal-500/20 border border-brand-400/30 flex items-center justify-center mx-auto mb-6 shadow-brand shadow-lg overflow-hidden">
            <img src="/AI-interview-svg-icon.png" alt="InterviewAI" className="w-full h-full object-cover rounded-xl" />
          </div>
          <h2 className="text-2xl sm:text-4xl md:text-5xl font-display font-bold text-white mb-3 sm:mb-4 px-2 leading-tight">
            Ready to nail your next interview?
          </h2>
          <p className="text-slate-400 text-sm sm:text-lg mb-6 sm:mb-8 px-2">
            Join 50,000+ candidates who transformed their interview performance and landed top software engineering offers.
          </p>
          <Link to="/register" className="btn-primary text-sm sm:text-base px-6 sm:px-10 py-3.5 sm:py-4 inline-flex shadow-xl shadow-brand-500/30">
            Get Started — It&apos;s Free <ArrowRight className="w-4 h-4 sm:w-5 sm:h-5 ml-1" />
          </Link>
        </motion.div>
      </section>

      {/* ── Footer ───────────────────────────────────────────────── */}
      <footer className="border-t border-surface-border py-10 sm:py-12 px-4 sm:px-6 bg-surface-card/20">
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-between gap-6 mb-8 text-center md:text-left">
            <Link to="/" className="flex items-center gap-2.5 group">
              <div className="w-8 h-8 rounded-xl overflow-hidden shadow-brand flex items-center justify-center border border-brand-400/30 group-hover:scale-105 transition-transform">
                <img src="/AI-interview-svg-icon.png" alt="InterviewAI" className="w-full h-full object-cover" />
              </div>
              <span className="font-display font-bold text-lg text-white">InterviewAI</span>
            </Link>
            <div className="flex flex-wrap items-center justify-center gap-4 sm:gap-6 text-xs sm:text-sm text-slate-400">
              <a href="#skills-section" className="hover:text-white transition-colors">Skills</a>
              <a href="#features-section" className="hover:text-white transition-colors">Features</a>
              <a href="#reviews-section" className="hover:text-white transition-colors">Reviews</a>
              <a href="#faq-section" className="hover:text-white transition-colors">FAQ</a>
              <Link to="/jobs" className="hover:text-white transition-colors">Jobs</Link>
            </div>
          </div>
          <div className="border-t border-surface-border/60 pt-6 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-500 text-center sm:text-left">
            <p>© 2026 InterviewAI. All rights reserved. Powered by Llama-3 & Groq.</p>
            <p>Built for engineers, students, and career switchers worldwide.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}

